version: "3"
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Tokyo
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - 8888:8888
    volumes:
      - .:/home/jovyan/work
      - ./.jupyter/.vimrc.json:/home/jovyan/.jupyter/lab/user-settings/jupyterlab-vimrc/vimrc.jupyterlab-settings
      - ./.jupyter/jupyter_notebook_config.json:/home/jovyan/.jupyter/jupyter_notebook_config.json
    command: start-notebook.sh --NotebookApp.token='' --notebook-dir=/home/jovyan/work
